"""refund_standard@v1: compiled from 16 traces of refund_request.

Signature: get_order>get_shipments>payments.refund>tickets.update>email.send
Generated by agentjit.compileplane.codegen. Do not hand-edit.
"""


def run(ctx, args):
    ctx.step(1)
    order = ctx.call('get_order', order_id=args['order_id'])
    ctx.bind('order', order)

    ctx.step(2)
    shipments = ctx.call('get_shipments', order_id=order['order_id'])
    ctx.bind('shipments', shipments)

    ctx.step(3)
    amount = ctx.call('compute_amount', discount=order['discount'], total=order['total'])['amount']
    ctx.bind('amount', amount)

    ctx.step(4)
    refund = ctx.call('payments.refund', amount=amount, charge_id=order['charge_id'])
    ctx.bind('refund', refund)

    ctx.step(5)
    ticket = ctx.call('tickets.update', status='resolved', ticket_id=order['ticket_id'])
    ctx.bind('ticket', ticket)

    ctx.step(6)
    email_body = ctx.hole('email_body', inputs={'order_id': args['order_id'], 'amount': amount})
    ctx.call('email.send', body=email_body, subject='Your refund has been processed', to=order['customer_email'])

    return {"ok": True}
