"""Code generator: template -> skill code conforming to docs/skill_abi.md (section 8.4).

With Claude available, the model drafts the code from the template, the ABI
and the v0 fixture skill as a worked example. Offline, a deterministic emitter
writes it. Either way the draft is untrusted: replay.py decides.
"""
from __future__ import annotations

import json
import pathlib
import re
from typing import Optional

from agentjit.common import config, llm

ROOT = pathlib.Path(__file__).resolve().parents[2]


def expr_for(spec: dict, steps: list[dict]) -> str:
    kind = spec["kind"]
    if kind == "const":
        return repr(spec["value"])
    if kind == "hole":
        return spec["hole"]
    if spec["source"] == "input":
        return f"args[{spec['input']!r}]"
    m = re.match(r"step(\d+)\.result(.*)", spec["path"])
    step = steps[int(m.group(1)) - 1]
    rest = m.group(2)
    if step["unwrap"] is not None:
        # pure op bound to its single field: step3.result.amount -> amount
        prefix = f".{step['unwrap']}"
        assert rest.startswith(prefix), spec["path"]
        rest = rest[len(prefix):]
        base = step["bind"]
    else:
        base = step["bind"]
    out = base
    for key, idx in re.findall(r"\.([A-Za-z_][A-Za-z0-9_]*)|\[(\d+)\]", rest):
        out += f"[{key!r}]" if key else f"[{idx}]"
    return out


def emit(template: dict, skill_id: str) -> str:
    steps = template["steps"]
    lines = [
        f'"""{skill_id}: compiled from {template["n"]} traces of {template["family"]}.',
        "",
        f"Signature: {template['signature']}",
        "Generated by agentjit.compileplane.codegen. Do not hand-edit.",
        '"""',
        "",
        "",
        "def run(ctx, args):",
    ]
    holes_by_pc = {h["pc"]: h for h in template["holes"]}
    for s in steps:
        lines.append(f"    ctx.step({s['pc']})")
        hole = holes_by_pc.get(s["pc"])
        if hole:
            inputs = ", ".join(f"{name!r}: {_input_expr(name, template)}" for name in hole["inputs"])
            lines.append(f"    {hole['name']} = ctx.hole({hole['name']!r}, inputs={{{inputs}}})")
        call_args = ", ".join(f"{a}={expr_for(spec, steps)}" for a, spec in sorted(s["args"].items()))
        call = f"ctx.call({s['name']!r}{', ' if call_args else ''}{call_args})"
        if s["unwrap"] is not None:
            lines.append(f"    {s['bind']} = {call}[{s['unwrap']!r}]")
        elif s["bind"]:
            lines.append(f"    {s['bind']} = {call}")
        else:
            lines.append(f"    {call}")
        if s["bind"]:
            lines.append(f"    ctx.bind({s['bind']!r}, {s['bind']})")
        lines.append("")
    lines.append('    return {"ok": True}')
    return "\n".join(lines) + "\n"


def _input_expr(name: str, template: dict) -> str:
    if name in template["inputs"]:
        return f"args[{name!r}]"
    return name  # a bound scalar from an earlier pure op


PROMPT = """You are the code generator of a tracing JIT for LLM agents. Write one Python module
implementing the template below. It must follow the skill ABI exactly.

Rules that replay will check:
- Expose exactly `def run(ctx, args):` and return {{"ok": True}}.
- Call ctx.step(pc) before each step, pcs 1..N exactly as in the template.
- One ctx.call per template step, same tool, same argument names and values. Pure ops
  (effect "pure") are called with ctx.call too.
- Bind each step result with ctx.bind(name, value) using the template's "bind" name. For a pure op
  with "unwrap", bind the unwrapped field (e.g. amount = ctx.call("compute_amount", ...)["amount"]).
- Parameters: "input" sources come from args[...]; "step" sources index the bound results.
- Holes: value = ctx.hole(name, inputs={{...}}) using the hole's listed inputs, before the call that uses it.
- No imports, no eval/exec, no other statements.

Skill ABI:
{abi}

Worked example (hand-written v0 skill for the same family):
{example}

Template:
{template}
{feedback}
Reply with only the module in one ```python block."""


def draft_with_llm(template: dict, skill_id: str, feedback: str = "") -> tuple[str, float]:
    abi = (ROOT / "docs" / "skill_abi.md").read_text()
    ex_path = ROOT / "fixtures" / "skills" / "refund_standard_v0.py"
    example = ex_path.read_text() if ex_path.exists() else "(none)"
    prompt = PROMPT.format(abi=abi, example=example, template=json.dumps(template, indent=1, default=str),
                           feedback=f"\nYour previous draft failed replay:\n{feedback}\n" if feedback else "")
    resp, usage = llm.create(config.CODEGEN_MODEL, max_tokens=8000, messages=[{"role": "user", "content": prompt}])
    text = llm.text_of(resp)
    m = re.search(r"```python\n(.*?)```", text, re.S)
    return (m.group(1) if m else text), usage.cost_usd


def draft(template: dict, skill_id: str, feedback: str = "") -> tuple[str, float, str]:
    """Returns (source, cost, method)."""
    if llm.available():
        src, cost = draft_with_llm(template, skill_id, feedback)
        return src, cost, "llm"
    return emit(template, skill_id), 0.0, "template"


def write(skill_name: str, version: int, source: str) -> str:
    path = pathlib.Path(config.SKILLS_DIR) / skill_name / f"v{version}.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source)
    return str(path)
